# Text style guide {#text}


For chart design guidance, see Section \@ref(chart). There is a GDS style guide
for all content published on gov.uk is available
[here](https://www.gov.uk/guidance/style-guide). The UKFSR guide is intended to
complement this.

## Accessibility

It is a legal obligation to make sure that our content is accessible, and this
applies to written content, graphics and tables. The Analysis Function has
guidance on [accessibility and plain
English](https://analysisfunction.civilservice.gov.uk/policy-store/making-analytical-publications-accessible/).

## Formatting styles

Use appropriate styles in Word, particularly for *headings*. Heading styles are critical to the structure of the web publications (see \@ref(web)), and building the table of contents in the print version (see \@ref(print)). If you dont use styles during drafting, its massive horrible job to retrofit them at the end when time is short.

**Note there is no need to worry about the specifics of formatting and the look of the text during drafting, in terms of font, colour, spacing etc. Concentrate on the content. Stick to marking text attributes such as heading level, bold, bulleted list etc. The Defra publication template and web publishing process will deal with the look of the finished product.** 

## Spelling/Word choice 

 - Say “UKFSR” or “this report”, not “the Report”. 

 - Use ‘coronavirus (COVID-19)’ in the text at first mention, then ‘COVID-19’ after that. 

 - government, UK government (not capitalised unless it’s Welsh or Scottish Government) 

 - other government departments  
 
 - Use ‘the’ when talking about ‘the FSA’, but don’t use ‘the’ when talking about ‘FSS’ 

 - FSA and FSS can be referred to collectively as “UK food safety bodies”, but not “food standards agencies.” 

 - Capitals when talking about ethnicities, e.g. ‘White’, ‘Black’ 

 - Disabled people and not people with disabilities
 
 - For the Ukraine War, refer to it as the "Ukraine War", "the war in Ukraine" or "Russia-Ukraine War".
 
 - Talking about Brexit:  

     - You can use the term ‘Brexit’ to provide historical context, but it’s better to use specific dates where possible. For example, use: 

         - ‘31 December 2020’ rather than ‘Brexit’ or ‘when the UK left the EU’ 
         - ‘before 31 December 2020’ rather than ‘during the transition period’ 
         - ‘after 1 January 2021’ rather than ‘after the transition period’ 


 - Dates: do not use a comma between the month and year: 4 June 2017 

 - white paper (lower case) 

 - Be very careful with the word “affordable”. Food is more affordable if it’s cheaper relative to incomes and other factors – if the price has gone down (but other factors mean it’s harder to afford) it’s simply _cheaper_. The general argument of the UKFSR is that over the last decade food *has got cheaper, but not more affordable* – so check this! 
 
 - Words to avoid:  

    - Robust 
    - Overarching 
    - Strengthen (unless we are actually strengthening an architectural structure) 
    - Tackling  
    - Going forward 
    - In order to (superfluous, never use it) 
    - impact (do not use this as a synonym for have an effect on, or influence) 
    - facilitate (instead, say something specific about how you’re helping) 
    - focusing 
    - key (unless it unlocks something. A subject/thing is not key - it’s probably important) 


## Sentence length 

 - Do not use long sentences. Check sentences with more than 25 words to see if you can split them to make them clearer. 
 
 
## URLs/Links {#urls}

See \@ref(refs) for references to academic reports. *Link to sources, data and
relevant online material liberally*, and when in doubt, link! Remember that this
is not necessarily relevant to the print edition but fundamental to the online
version. Todays readers expect to be able to click through to verify or explore
further the data and other sources we refer to. It is fundamental to the
credibility of the report.

Alongside from the principle of 'link liberally', is the principle of 'link
sensibly'. This simply means point to the place where a user might generally
expect to go when they click. This might be a specific document/report, a
summary page containing relevant content, or even the home page for an
organisation. Use your judgement and put yourself in the position of an end
user. Some examples:

- **Data links:** Every chart must have a csv preview link. See Section \@ref(data) for
guidance on that. In addition all sources must be linked to. Curious users might
want to explore the raw data sources beyond our curated csvs if they are happy
to do so. Either way they should have a link to the owner/producers of the data
so we need to add links to unedited sources. Which leads on to...

- **Collection pages:** Most statistics and regular gov.uk publications have a 'collection page' which is a place to collate current and previous versions. Consider the difference between the [CPI collection  page](https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/consumerpriceinflation/previousReleases) which always shows the catalogue of recent publications, and an individual [release](https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/consumerpriceinflation/september2023). Generally the collection page is more future proof for users, unless you are making a reference to a specific edition in the UKFSR. The UKFSR has its own [collection page](https://www.gov.uk/government/collections/united-kingdom-food-security-report), although at the time of writing it only contains the UKFSR 2021 - eventually this will become an archive and repository of the most recent analysis.

- **General links:** If there is no logical place to go, link to the organisation home page or somewhere else sensible, eg [uktradeinfo](https://www.uktradeinfo.com/trade-data/ots-custom-table/). Keep in mind that these links need to be relevant for at least three years - in 2027 will they still take people to places that are useful? Its OK to link to time sensitive material such as dated news reports but consider whether links are persistent and will not become stale.


## References {#refs}

See \@ref(urls) for general linking guidance. Include a reference in-text after
the relevant sentence/paragraph. References should follow the style guide. When
writing a reference:

 - do not use italics 
 - use single quote marks around titles 
 - write out abbreviations in full: page not p, Nutrition Journal not Nutr J. 
 - use plain English, for example use ‘and others’ not ‘et al’ 
 - do not use full stops after initials or at the end of the reference 
 
*References can also be included as footnotes, particularly where too long or unwieldy for convenience in text.* 

If the reference is available online, make the title a link and include the date
you accessed the online version. For example:

 - Although food availability is increasing in low and middle-income countries, fruit and vegetables are still high-value items, meaning fats and sweeteners will make up large parts of the increase in consumption (FAO. [‘OECD-FAO Agricultural Outlook 2021-2030’](https://www.fao.org/3/cb5332en/cb5332en.pdf) 2021).  

 - There is a recurring reference through multiple themes to AUK, check for consistency to make sure it is referenced as follows: (Defra. [‘Agriculture in the United Kingdom 2020’](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1056618/AUK2020_22feb22.pdf) 2020)  

 - Example given on gov.uk: Corallo AN and others. [‘A systematic review of medical practice variation in OECD countries’](https://www.sciencedirect.com/journal/health-policy) Health Policy 2014: volume 114, pages 5 to 14. 


## Acronyms {#acronyms-text}

 - Write out acronym for the first time in each theme, put abbreviation in brackets, then use abbreviation going forwards. This means acronyms should be re-introduced anew between the introduction and themes.
 
 - Note that for web publishing, acronyms need a little more work (see \@ref(acronyms-web)). **Its a good idea to maintain a master list of all acronyms and their full descriptions** - it will help speed up the publishing preparation. 

## Labelling data

 - Each data set (table, bar chart, etc.) should be labelled as ‘Figure’ with the corresponding indicator number and a letter. For instance, for data in theme 1, this could look like ‘Figure 1.1.2a’, Figure ‘1.1.2b’, etc.


## Indicator section headings 

Each indicator should have the following headings (check for consistent spelling): 

 - **Headline** 
   - Brief summary of the key findings in the indicator – seen from a “what this means for food security lens” (ie, ‘the UK produces around 80% of the wheat it consumes; average production is stable with some fluctuations due to weather’ rather than ‘the UK produces x million tons of wheat’) 
   
   

 - **Context and Rationale**
   - Background information for the data and explanation why this data matters for UK food security 


 - **Data and Assessment**
 
   - Data and source 
      - If multiple sources, list as follows:  
      - Source: FSA; FSS 
   - Description of what the data in the ‘Data and Assessment’ section is showing 


 - **Rating and Trends / Direction of Travel**
   - State any visible trends in the data: ie, things appear to be stable, or to fluctuate, or have a clear positive upward/downward trend, or it’s not clear from available data. Note also any important external factors. 
   

## The 'Voice'

 - Avoid using sentences such as ‘We produce x amount of wheat’. The tone should be more neutral, i.e. write ‘The UK produces x amount of wheat’.
 

## e.g. / i.e. / etc.  

 - **e.g.** can sometimes be read aloud as ‘egg’ by screen reading software. Instead use ‘for example’ or ‘such as’ or ‘like’ or ‘including’ - whichever works best in the specific context. 
 - **etc** can usually be avoided. Try using ‘for example’ or ‘such as’ or ‘like’ or ‘including’. Never use etc at the end of a list starting with these words. 
 - **ie** - used to clarify a sentence - is not always well understood. Try (re)writing sentences to avoid the need to use it. If that is not possible, use an alternative such as ‘meaning’ or ‘that is’. 
 

## Symbols 

 - '&' use 'and', e.g. Context and rationale 
 - '/' use 'and', e.g 2007/2008 = 2007 and 2008 
 - '-' use 'to' (for example in dates), e.g. 2011-14 = 2011 to 2014
 

## Numbers  

 - Write all other numbers in numerals (including 2 to 9) except where it’s part of a common expression like ‘one or two of them’ where numerals would look strange. 
 - Use a % sign for percentages: 50% 
 - Use ‘500 to 900’ and not ‘500-900’ (except in tables) 


## Quotation marks:  

Use single quotes 

 - in headlines 
 - for unusual terms 
 - when referring to words 
 - when referring to publications

Use double quotes: 

 - Use double quotes in body text for direct quotations
 
