# Chart Style Guide {#chart}

This section will cover guidance on chart design and themes. For the text
styleguide, see Section \@ref(text). There is general guidance on chart design
produced by the [Analysis Function](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-charts/).

**Please refer to Section \@ref(data) on preparing data for charting and publication as preview csv data.**

## Colours

The UKFSR uses the Analysis Function palette as recommended [here](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/). There is an R package, `afcolours` available on CRAN, which helps with implementing the [palette](https://best-practice-and-impact.github.io/afcolours/).

There are a maximum of 6 colours available in the palette for categorical
variables. This means that an individual chart may not have more than 6 series.

## Font

The gov.uk site uses a custom font, GDSTransport. Its preferable to ensure that
text in graphics also uses this font. Example R code below:

```
library(showtext)

font_add(family = "GDS Transport Website",
         regular = "font/GDSTransportWebsite.ttf",
         bold = "font/GDSTransportWebsite-Bold.ttf")

showtext_auto()
```

## Chart context

Each chart is accompanied by some additional features:

- CSV: the csv of the chart data is required for a preview/download link
- URL to source: the default is a link to collection pages wherever possible.

## Resolution/format

Graphics must be saved in  both SVG and PNG format, as required by gov.uk and
for PDF respectively. See Section \@ref(web) for more details.

## Helpers

The [`ukfsr`](https://github.com/FoodchainStats/ukfsr) package contains functions
to assist with preparing the report.  There is a `theme_ukfsr()` theme for chart
styling, plus some functions to assist with saving charts and data in the S3
bucket.