# (APPENDIX) Appendix {-}

# Miscellaneous

## Sharepoint management practice

Its assumed that the report sections will be Word documents hosted on Sharepoint and edited in prallel by multiple authors. Sharepoint retains old versions, however it may be prudent to make a regular backup copy and store in a separate folder. There is also some kind of limit to the number of track changes and comments that Word can retain, which we ran up against a few times last time. Its probably wise to accept all track changes on a relatively regular basis and save the docs to simplify them. This is probably a matter of trial and error. See also Section \@ref(print) on physical print which has some thoughts on file management at the end of the project. 

## OSR feedback on UKFSR2021

[Here.](https://osr.statisticsauthority.gov.uk/correspondence/mark-pont-to-ian-lonsdale-united-kingdom-food-security-report/)

## General legal guidance from 2024

### Legal basis

[Agriculture Act 2020](https://www.legislation.gov.uk/ukpga/2020/21/part/2/chapter/1/enacted)

### Publication deadline

[from legal comments 11/01/2024]

The date you should lay the report is actually 3 years from the date of the last
report so that would be the 15 December 2024 (although note that this is a
Sunday so the last sitting day before this date would be appropriate). There is
no reason not to publish before this date if needed and it would be advisable
not to leave it to the last possible date. Section 19 of the Agriculture Act
2020 states that **a new UKFSR is required “at least once every three years”**. We
think that the safest way to interpret this would be that each UKFSR laying
starts a three-year ‘clock’ by which another UKFSR must be published. As the
first UKFSR was laid in Parliament on December 16 2021, the three-year clock
means that the next must be laid by December 15 2024, but can be any time
before. If UKFSR2 is instead laid on, for instance, September 1 2024, UKFSR3
will have to be laid by August 31 2027. 

Also please note that although preferable, **Parliament does not absolutely have
to be sitting for a paper to be laid.** This has previously been considered by
policy and legal and whilst the UKFSR was published as an Act paper, if it must
be published on a non-sitting day in order to avoid breaching statutory duties,
Parliamentary Team consider that it could in exceptional circumstances be laid
as a Command Paper with the full knowledge of the Journal Office and with the
relevant changes made to its cover. This may not be necessary in future but for
now it is advisable.

**Further, the UKFSR is Official Statistics**, which require notice of publication
at least four weeks before the intended publication date, and publication on
that date. Once the date is pre-notified, any failure to publish on that date
will invite scrutiny from the Office of Statistical Regulation. This does not
touch on any of the other rules, but if coming out on the same day should take
account of the time it takes to lay documents in Parliament, so the next UKFSR
should probably commit to publish at noon or so rather than 0930.



#### Late laying of the report

If the report is laid later than deadline date there would be a breach of this
statutory duty. The risk of a legal challenge being brought (our assessment is
that there would be a low risk (less than 30%)) would depend on the
circumstances that caused the delay and the length of the delay. However, if it
is brought the chances of successful challenge are medium-high (50-70%) given
that there is a clear statutory duty to publish by a certain date. We could
perhaps mitigate this depending on the circumstances which would lower the risk.
For example, the Courts would likely look more favourably on SoS if the reason
for delay was an election. However, if you know there will be an election then
steps should be taken to avoid delay as much as possible. In short, unavoidable
circumstances would look more favourable to the Courts than avoidable ones.


#### Environmental principles policy 
We have considered whether the Environmental principles policy would apply here. Section 17(5) of the Environment Act 2021 sets out 5 principles that ministers will need to consider when making policy, namely:

 - integration principle
 - prevention principle
 - rectification at source principle
 - polluter pays principle
 - precautionary principle

Whilst any particular concerns arising from considerations in the EPP statement will likely not apply when collecting data and compiling the report, any policy development that follows on from the reports’ findings should have due regard to the principles. This is just something to flag at this stage.

#### General considerations
Lastly, and as a general legal point, if the contents of the report were to be challenged, the ground would likely be rationality. It is therefore important that information sources are referenced correctly and checked. The 2021 report will of course provide an excellent starting point and seeing as that was not challenged, adopting a similar approach would be sensible.

